#!/usr/bin/env sh

# This executable is a stub for backwards compatibility. Consider installing this code as a python package with `pip` and calling `pernosco` directly.
DIR="$(dirname "$(realpath "$0")")"
PYTHONPATH=$DIR/src python3 "$DIR/src/pernosco_on_prem/pernosco.py" "$@"
